const lang = {
  en: {
    search: "Search",
    gptSearchPlaceholder: "What would you like to watch today?",
    nowPlaying: "Now Playing",
    upcomingMovies: "Upcoming Movies",
    popular: "Popular",
    topRated: "Top Rated",
    airingTodayShows: "Airing Today Shows",
    popularShows: "Popular Shows",
    topRatedTvShows: "Top Rated TV Shows",
    play: "Play",
    info: "More Info",
    home : "Home",
    gptSearch : "Search with GPT",
  },
  hindi: {
    search: "खोज",
    gptSearchPlaceholder: "आज आप क्या देखना चाहेंगे?",
    nowPlaying: "अब फिल्में",
    upcomingMovies: "आने वाली फ़िल्में",
    popular: "लोकप्रिय",
    topRated: "सर्वश्रेष्ठ रेटेड",
    airingTodayShows: "आज प्रसारित शो",
    popularShows: "लोकप्रिय शो",
    topRatedTvShows: "सर्वश्रेष्ठ रेटेड टीवी शो",
    play: "चलाएं",
    info: "अधिक जानकारी",
     home: "मुखपृष्ठ", 
     gptSearch: "जीपीटी खोज"
  },
  spanish: {
    search: "Buscar",
    gptSearchPlaceholder: "¿Qué te gustaría ver hoy?",
    nowPlaying: "Películas en cartelera",
    upcomingMovies: "Próximas películas",
    popular: "Popular",
    topRated: "Más valoradas",
    airingTodayShows: "Programas que se emiten hoy",
    popularShows: "Programas populares",
    topRatedTvShows: "Programas de TV mejor valorados",
    play: "Reproducir",
    info: "Más información"
  },
  chinese: {
    search: "搜索",
    gptSearchPlaceholder: "今天想看什么？",
    nowPlaying: "正在播放",
    upcomingMovies: "即将上映",
    popular: "热门",
    topRated: "高评分",
    airingTodayShows: "今日播出节目",
    popularShows: "热门节目",
    topRatedTvShows: "高评分电视节目",
    play: "播放",
    info: "更多信息"
  },
  french: {
    search: "Rechercher",
    gptSearchPlaceholder: "Que voulez-vous regarder aujourd'hui ?",
    nowPlaying: "À l'affiche",
    upcomingMovies: "Films à venir",
    popular: "Populaire",
    topRated: "Les mieux notés",
    airingTodayShows: "Émissions d'aujourd'hui",
    popularShows: "Émissions populaires",
    topRatedTvShows: "Les meilleures émissions TV",
    play: "Jouer",
    info: "Plus d'informations"
  },
  arabic: {
    search: "بحث",
    gptSearchPlaceholder: "ماذا تريد أن تشاهد اليوم؟",
    nowPlaying: "يعرض الآن",
    upcomingMovies: "الأفلام القادمة",
    popular: "شائع",
    topRated: "الأعلى تقييمًا",
    airingTodayShows: "العروض التي تبث اليوم",
    popularShows: "عروض شائعة",
    topRatedTvShows: "أفضل العروض التلفزيونية تقييمًا",
    play: "تشغيل",
    info: "مزيد من المعلومات"
  },
  bengali: {
    search: "অনুসন্ধান",
    gptSearchPlaceholder: "আজ আপনি কী দেখতে চান?",
    nowPlaying: "এখন চলছে",
    upcomingMovies: "আসন্ন চলচ্চিত্র",
    popular: "জনপ্রিয়",
    topRated: "শ্রেষ্ঠ রেটেড",
    airingTodayShows: "আজকের শো",
    popularShows: "জনপ্রিয় শো",
    topRatedTvShows: "শ্রেষ্ঠ রেটেড টিভি শো",
    play: "চালান",
    info: "আরও তথ্য"
  },
  russian: {
    search: "Поиск",
    gptSearchPlaceholder: "Что вы хотите посмотреть сегодня?",
    nowPlaying: "Сейчас в кино",
    upcomingMovies: "Скоро в кино",
    popular: "Популярные",
    topRated: "Самые рейтинговые",
    airingTodayShows: "Сегодня в эфире",
    popularShows: "Популярные шоу",
    topRatedTvShows: "Лучшие телешоу",
    play: "Воспроизвести",
    info: "Подробнее"
  },
  portuguese: {
    search: "Buscar",
    gptSearchPlaceholder: "O que você gostaria de assistir hoje?",
    nowPlaying: "Em exibição",
    upcomingMovies: "Próximos filmes",
    popular: "Popular",
    topRated: "Mais bem avaliados",
    airingTodayShows: "Programas que vão ao ar hoje",
    popularShows: "Programas populares",
    topRatedTvShows: "Melhores programas de TV",
    play: "Reproduzir",
    info: "Mais informações"
  },
  urdu: {
    search: "تلاش کریں",
    gptSearchPlaceholder: "آج آپ کیا دیکھنا چاہیں گے؟",
    nowPlaying: "ابھی چل رہا ہے",
    upcomingMovies: "آنے والی فلمیں",
    popular: "مشہور",
    topRated: "اعلی درجہ بندی",
    airingTodayShows: "آج کے شوز",
    popularShows: "مشہور شوز",
    topRatedTvShows: "اعلی درجہ بندی والے ٹی وی شوز",
    play: "چلائیں",
    info: "مزید معلومات"
  },
  indonesian: {
    search: "Cari",
    gptSearchPlaceholder: "Apa yang ingin Anda tonton hari ini?",
    nowPlaying: "Sedang Tayang",
    upcomingMovies: "Film Mendatang",
    popular: "Populer",
    topRated: "Peringkat Teratas",
    airingTodayShows: "Acara Hari Ini",
    popularShows: "Acara Populer",
    topRatedTvShows: "Acara TV Terbaik",
    play: "Putar",
    info: "Info Lebih Lanjut"
  },
  german: {
    search: "Suchen",
    gptSearchPlaceholder: "Was möchten Sie heute ansehen?",
    nowPlaying: "Jetzt im Kino",
    upcomingMovies: "Kommende Filme",
    popular: "Beliebt",
    topRated: "Am besten bewertet",
    airingTodayShows: "Heute im Programm",
    popularShows: "Beliebte Shows",
    topRatedTvShows: "Top-bewertete TV-Shows",
    play: "Abspielen",
    info: "Mehr Infos"
  },
  japanese: {
    search: "検索",
    gptSearchPlaceholder: "今日は何を見たいですか？",
    nowPlaying: "上映中",
    upcomingMovies: "近日公開",
    popular: "人気",
    topRated: "高評価",
    airingTodayShows: "今日放送の番組",
    popularShows: "人気番組",
    topRatedTvShows: "高評価のテレビ番組",
    play: "再生",
    info: "詳細情報"
  },
  tamil: {
    search: "தேடல்",
    gptSearchPlaceholder: "இன்று நீங்கள் என்ன பார்க்க விரும்புகிறீர்கள்?",
    nowPlaying: "இப்போது விளையாடுகிறது",
    upcomingMovies: "வரவிருக்கும் படங்கள்",
    popular: "பிரபலமான",
    topRated: "சிறந்த மதிப்பீடு",
    airingTodayShows: "இன்று ஒளிபரப்பாகும் நிகழ்ச்சிகள்",
    popularShows: "பிரபலமான நிகழ்ச்சிகள்",
    topRatedTvShows: "சிறந்த மதிப்பீடு டிவி நிகழ்ச்சிகள்",
    play: "விளையாடு",
    info: "மேலும் தகவல்"
  },
  telugu: {
    search: "వెతకండి",
    gptSearchPlaceholder: "ఈ రోజు మీరు ఏమి చూడాలనుకుంటున్నారు?",
    nowPlaying: "ఇప్పుడు ప్రదర్శనలో ఉంది",
    upcomingMovies: "రాబోయే సినిమాలు",
    popular: "ప్రసిద్ధ",
    topRated: "అత్యుత్తమంగా రేట్ చేయబడింది",
    airingTodayShows: "ఈ రోజు ప్రసారం షోలు",
    popularShows: "ప్రసిద్ధ షోలు",
    topRatedTvShows: "అత్యుత్తమంగా రేట్ చేయబడిన టీవీ షోలు",
    play: "ప్లే",
    info: "మరింత సమాచారం"
  },
  turkish: {
    search: "Ara",
    gptSearchPlaceholder: "Bugün ne izlemek istersiniz?",
    nowPlaying: "Şimdi Oynayanlar",
    upcomingMovies: "Yaklaşan Filmler",
    popular: "Popüler",
    topRated: "En Çok Beğenilenler",
    airingTodayShows: "Bugün Yayınlanan Şovlar",
    popularShows: "Popüler Şovlar",
    topRatedTvShows: "En Beğenilen TV Şovları",
    play: "Oynat",
    info: "Daha Fazla Bilgi"
  },
  vietnamese: {
    search: "Tìm kiếm",
    gptSearchPlaceholder: "Hôm nay bạn muốn xem gì?",
    nowPlaying: "Đang Chiếu",
    upcomingMovies: "Phim Sắp Ra Mắt",
    popular: "Phổ biến",
    topRated: "Đánh giá cao nhất",
    airingTodayShows: "Chương trình phát sóng hôm nay",
    popularShows: "Chương trình phổ biến",
    topRatedTvShows: "Chương trình truyền hình đánh giá cao",
    play: "Phát",
    info: "Thông tin thêm"
  }
};

export default lang;
